### ISSUE TITLE
Mechs load shells ignoring mortairs rules

### ISSUE THREAD

**Issue by OldRomeo** [emipa606/ReadyThoseGuns#2]
Hello, mate. Thanks for awesome mod. I've tried to start new colony with your mod for lone mechanitor, but looks like with mod mechs ignore mortairs shell rules. They load the nearest even if e.g. emp shell is not allowed to be put to the mortair

**Comment by emipa606** [comment]
Unfortunately this is a limitation or more like a bug in the vanilla code. 
The method that looks for available ammo only checks the storage-settings for a mortar if the pawn doing the reloading is considered a Colonist. As mechs are defined as ColonyMechs it just ignores the settings.
Ill report this as a bug and hopefully they can fix it in a future update.

**Comment by OldRomeo** [comment]
Thanks anyways! Will be highly appreciated if you mention it on mod page
